language: nix
script:
- git clone https://github.com/mozilla/nixpkgs-mozilla.git
- pushd nixpkgs-mozilla
- ./rust-overlay-install.sh
- nix-env -iA nixpkgs.latest.rustChannels.stable.rust
- popd
- cargo test
